name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # 在推送到 main 分支時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: YOUR_PROJECT_ID

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --quiet