name: CI/CD to Google Compute Engine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to GCE
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCE_INSTANCE: instance-20240529-070416

    steps:
    # ... (previous steps remain the same)

    - name: Get instance zone
      run: |
        ZONE=$(gcloud compute instances list --filter="name=${{ env.GCE_INSTANCE }}" --format="get(zone)" --quiet)
        echo "GCE_INSTANCE_ZONE=$ZONE" >> $GITHUB_ENV

    - name: Deploy to Compute Engine
      run: |
        gcloud compute scp --recurse --zone=${{ env.GCE_INSTANCE_ZONE }} ./* ${{ env.GCE_INSTANCE }}:/tmp/telegram-bot-temp
        gcloud compute ssh --zone=${{ env.GCE_INSTANCE_ZONE }} ${{ env.GCE_INSTANCE }} --command="
          sudo rm -rf /home/cruz/telegram-bot
          sudo mv /tmp/telegram-bot-temp /home/cruz/telegram-bot
          sudo chown -R cruz:cruz /home/cruz/telegram-bot
          cd /home/cruz/telegram-bot &&
          sudo docker build -t telegram-bot . &&
          sudo docker stop telegram-bot-container || true &&
          sudo docker rm telegram-bot-container || true &&
          sudo docker run -d --name telegram-bot-container \
            -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
            -e GOOGLE_SPREADSHEET_ID=${{ secrets.GOOGLE_SPREADSHEET_ID }} \
            telegram-bot
        "