name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # 在推送到 main 分支時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: cool-ruler-419911
        install_components: app-engine-python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --quiet

    - name: Enable Metadata Server Access
      run: |
        curl -X PUT -H "Metadata-Flavor: Google" \
             "http://metadata.google.internal/computeMetadata/v1/instance/guest-attributes/enable" \
             -d "true"